import { NextResponse } from "next/server";
import nodemailer from "nodemailer";

const EMAIL_RECIPIENTS = ["max.young@leadseveryday.co.uk"];

// Existing Google Apps Script sheet endpoint (keeps the current spreadsheet in sync)
const SCRIPT_URL =
  "https://script.google.com/macros/s/AKfycbyqrLt-Ev-uGANg5Qa7bdwU4uZG5EW_2EcNkX6N9l9Xj0n_dQVR24leOtdHEenXVnwQ/exec";

// Human-readable labels for the email summary
const FIELD_LABELS: Record<string, string> = {
  name: "Name",
  company: "Company",
  email: "Email",
  trade: "Trade / industry",
  tenure: "Time with LED",
  g_other: "Other growth",
  turnover_before: "Turnover — before (£/mo)",
  turnover_now: "Turnover — now (£/mo)",
  employees_before: "Employees — before",
  employees_now: "Employees — now",
  vans_before: "Vans — before",
  vans_now: "Vans — now",
  jobs_before: "Jobs/mo — before",
  jobs_now: "Jobs/mo — now",
  jobvalue_before: "Avg job value — before (£)",
  jobvalue_now: "Avg job value — now (£)",
  cpl_before: "Cost per lead — before (£)",
  cpl_now: "Cost per lead — now (£)",
  r_quality: "Rating — lead quality",
  r_quantity: "Rating — lead quantity",
  r_conversion: "Rating — conversion",
  r_service: "Rating — customer service",
  r_satisfaction: "Rating — overall satisfaction",
  nps: "NPS — likely to recommend",
  pct_work: "% of work from LED",
  jobs_generated: "Jobs generated by LED",
  biggest_job_value: "Biggest job won (£)",
  biggest_achievement: "Proudest achievement",
  story: "Growth story",
  c_testimonial: "Consent — testimonial",
  c_video: "Consent — video",
  c_visit: "Consent — filming visit",
  c_logo: "Consent — logo/photos",
};

const GROWTH_LABELS: Record<string, string> = {
  g_revenue: "Increased monthly revenue",
  g_prices: "Increased prices",
  g_staff: "Hired more staff",
  g_branch: "Opened another branch",
  g_vans: "Added more vans",
  g_quiet: "Reduced quiet periods",
  g_areas: "Expanded into new areas",
  g_biggerjobs: "Won bigger jobs",
  g_fullybooked: "Become fully booked",
  g_profit: "Improved profitability",
  g_newservice: "Started a new service",
  h_leftprovider: "Left another lead provider",
  h_boughtvehicle: "Bought another vehicle",
  h_reducedads: "Reduced Google Ads spend",
  h_apprentice: "Hired an apprentice",
  h_reducedreferrals: "Reduced reliance on referrals",
  h_fulltimestaff: "Hired more full-time staff",
  h_gonefulltime: "Gone full-time",
  h_worklife: "Improved work-life balance",
};

function esc(value: unknown) {
  return String(value ?? "")
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;");
}

export async function POST(request: Request) {
  try {
    const body = (await request.json()) as Record<string, string>;

    // Honeypot — silently accept and drop
    if (body.website_hp) {
      return NextResponse.json({ ok: true });
    }

    const name = (body.name || "").trim();
    const email = (body.email || "").trim();
    if (!name || !/^[^@\s]+@[^@\s]+\.[^@\s]+$/.test(email)) {
      return NextResponse.json(
        { error: "A name and valid email are required." },
        { status: 400 }
      );
    }

    delete body.website_hp;

    // 1) Keep the existing Google Sheet in sync (form-encoded, as the sheet expects)
    const sheetPromise = fetch(SCRIPT_URL, {
      method: "POST",
      headers: {
        "Content-Type": "application/x-www-form-urlencoded;charset=UTF-8",
      },
      body: new URLSearchParams(body).toString(),
    }).catch((err) => {
      console.error("Growth review — sheet sync error:", err);
    });

    // 2) Email the team a readable summary
    const ticked = Object.keys(GROWTH_LABELS)
      .filter((k) => body[k])
      .map((k) => GROWTH_LABELS[k]);

    const detailRows = Object.entries(FIELD_LABELS)
      .filter(([key]) => body[key] && String(body[key]).trim() !== "")
      .map(
        ([key, label]) =>
          `<tr><td style="padding:8px 12px;color:#94a3b8;font-size:13px;border-bottom:1px solid #1e293b;white-space:nowrap;">${label}</td><td style="padding:8px 12px;color:#e2e8f0;font-size:13px;border-bottom:1px solid #1e293b;">${esc(
            body[key]
          )}</td></tr>`
      )
      .join("");

    const consentYes = ["c_testimonial", "c_video", "c_visit", "c_logo"]
      .filter((k) => body[k] === "Yes")
      .map((k) => FIELD_LABELS[k].replace("Consent — ", ""));

    let emailPromise: Promise<unknown> = Promise.resolve();
    if (process.env.SMTP_HOST) {
      const transporter = nodemailer.createTransport({
        host: process.env.SMTP_HOST,
        port: Number(process.env.SMTP_PORT) || 587,
        secure: Number(process.env.SMTP_PORT) === 465,
        auth: { user: process.env.SMTP_USER, pass: process.env.SMTP_PASS },
      });

      emailPromise = transporter
        .sendMail({
          from: `Leads Every Day <${process.env.SMTP_FROM || process.env.SMTP_USER}>`,
          to: EMAIL_RECIPIENTS.join(", "),
          replyTo: email,
          subject: `Growth Review: ${body.company || name}`,
          html: `<!DOCTYPE html>
<html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"></head>
<body style="margin:0;padding:0;background-color:#0f172a;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,Helvetica,Arial,sans-serif;">
<table width="100%" cellpadding="0" cellspacing="0" style="background-color:#0f172a;padding:24px 16px;">
<tr><td align="center">
<table width="600" cellpadding="0" cellspacing="0" style="max-width:600px;width:100%;">
<tr><td style="padding:24px 32px;background-color:#1e293b;border-radius:12px 12px 0 0;border-bottom:2px solid #22c55e;">
  <img src="https://www.leadseveryday.co.uk/leads-everyday-neg.png" alt="Leads Every Day" width="180" height="21" style="display:block;border:0;" />
</td></tr>
<tr><td style="padding:24px 32px 0;background-color:#1e293b;">
  <table cellpadding="0" cellspacing="0"><tr>
    <td style="background-color:#22c55e;color:#fff;font-size:11px;font-weight:700;letter-spacing:1px;text-transform:uppercase;padding:5px 12px;border-radius:4px;">Growth Review</td>
    <td style="padding-left:12px;color:#94a3b8;font-size:13px;">${new Date().toLocaleDateString(
      "en-GB",
      {
        weekday: "short",
        day: "numeric",
        month: "short",
        year: "numeric",
        hour: "2-digit",
        minute: "2-digit",
      }
    )}</td>
  </tr></table>
</td></tr>
<tr><td style="padding:16px 32px 8px;background-color:#1e293b;">
  <h1 style="margin:0;color:#f1f5f9;font-size:20px;">${esc(body.company || name)}</h1>
  <p style="margin:4px 0 0;color:#94a3b8;font-size:13px;">${esc(name)} · ${esc(email)}</p>
</td></tr>
${
  ticked.length
    ? `<tr><td style="padding:8px 32px 16px;background-color:#1e293b;">
  <p style="margin:0 0 8px;color:#94a3b8;font-size:12px;text-transform:uppercase;letter-spacing:1px;">Growth achieved</p>
  ${ticked
    .map(
      (t) =>
        `<span style="display:inline-block;background-color:#0f172a;color:#22c55e;font-size:12px;padding:4px 10px;border-radius:4px;margin:0 6px 6px 0;">${esc(
          t
        )}</span>`
    )
    .join("")}
</td></tr>`
    : ""
}
<tr><td style="padding:0 32px 24px;background-color:#1e293b;border-radius:0 0 12px 12px;">
  <table width="100%" cellpadding="0" cellspacing="0" style="border-collapse:collapse;">${detailRows}</table>
  ${
    consentYes.length
      ? `<p style="margin:16px 0 0;color:#22c55e;font-size:13px;font-weight:600;">✅ Happy to feature: ${consentYes.join(
          ", "
        )}</p>`
      : ""
  }
</td></tr>
</table>
</td></tr>
</table>
</body></html>`,
        })
        .catch((err) => {
          console.error("Growth review — email error:", err);
        });
    }

    await Promise.allSettled([sheetPromise, emailPromise]);

    return NextResponse.json({ ok: true });
  } catch (err) {
    console.error("Growth review — handler error:", err);
    return NextResponse.json(
      { error: "Something went wrong. Please try again." },
      { status: 500 }
    );
  }
}
